const DEFAULTS={names:['Cory','Lucas','Calvin'],rates:{week:850,weekday:106.25,weekend:159.38,holiday:175}};
const STORE='onCallPayroll.v1',HISTORY='onCallPayroll.history.v1',SETTINGS='onCallPayroll.settings.v1';
const $=s=>document.querySelector(s);const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const parseKey=k=>{const [y,m,d]=k.split('-').map(Number);return new Date(y,m-1,d)};
const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
function startOfWeek(d=new Date()){const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-x.getDay());return x}
function initialWeek(){const now=new Date(),sun=startOfWeek(now);return now.getDay()===1?addDays(sun,-7):sun}
let settings=loadJson(SETTINGS,DEFAULTS);let weekStart=initialWeek();let active=0;let state={};let histories=loadJson(HISTORY,[]);
function loadJson(k,f){try{return JSON.parse(localStorage.getItem(k))??structuredClone(f)}catch{return structuredClone(f)}}
function save(){localStorage.setItem(STORE,JSON.stringify(state));localStorage.setItem(SETTINGS,JSON.stringify(settings));localStorage.setItem(HISTORY,JSON.stringify(histories))}
function weekState(){const k=dateKey(weekStart);state[k]??={days:{}};return state[k]}
function nthWeekday(y,m,weekday,n){const d=new Date(y,m,1);return 1+((7+weekday-d.getDay())%7)+(n-1)*7}
function lastWeekday(y,m,weekday){const d=new Date(y,m+1,0);return d.getDate()-((7+d.getDay()-weekday)%7)}
function holidayName(d){const y=d.getFullYear(),m=d.getMonth(),day=d.getDate();if(m===0&&day===1)return "New Year's Day";if(m===4&&day===lastWeekday(y,4,1))return 'Memorial Day';if(m===6&&day===4)return 'Independence Day';if(m===8&&day===nthWeekday(y,8,1,1))return 'Labor Day';if(m===10&&day===nthWeekday(y,10,4,4))return 'Thanksgiving';if(m===10&&day===nthWeekday(y,10,5,4))return 'Day after Thanksgiving';if(m===11&&day===25)return 'Christmas';return ''}
function dayData(d){const rec=weekState().days[dateKey(d)]||{};return {tech:Number.isInteger(rec.tech)?rec.tech:null,holiday:rec.holiday??Boolean(holidayName(d)),manualHoliday:'holiday' in rec}}
function setDayData(d,data){weekState().days[dateKey(d)]={...data};save()}
function baseAllocations(){const days=Array.from({length:7},(_,i)=>addDays(weekStart,i));const assigned=days.map((d,i)=>({d,i,...dayData(d)})).filter(x=>x.tech!==null);const full=assigned.length===7;const exactByTech=settings.names.map(()=>0);assigned.forEach(x=>exactByTech[x.tech]+=x.i===0||x.i===6?settings.rates.weekend:settings.rates.weekday);let cents=exactByTech.map(v=>Math.round(v*100));if(full){const target=Math.round(settings.rates.week*100),diff=target-cents.reduce((a,b)=>a+b,0);if(diff){const candidates=cents.map((v,i)=>({i,v,days:assigned.filter(x=>x.tech===i).length})).filter(x=>x.v>0).sort((a,b)=>b.days-a.days||b.v-a.v);if(candidates.length)cents[candidates[0].i]+=diff}}return {days,assigned,cents,full}}
function calculations(){const a=baseAllocations();const premiums=settings.names.map(()=>0);a.assigned.forEach(x=>{if(x.holiday)premiums[x.tech]+=settings.rates.holiday});const totals=a.cents.map((c,i)=>c/100+premiums[i]);return {...a,premiums,totals,total:totals.reduce((x,y)=>x+y,0)}}
function rangeLabel(){const end=addDays(weekStart,6);const fmt=new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'});return `${fmt.format(weekStart)} – ${fmt.format(end)}, ${end.getFullYear()}`}
function compactDates(indices){if(!indices.length)return '';const ds=indices.map(i=>addDays(weekStart,i));const out=[];let start=0;for(let i=1;i<=ds.length;i++){if(i===ds.length||(ds[i]-ds[i-1])/86400000!==1){const a=ds[start],b=ds[i-1],f=d=>`${d.getMonth()+1}/${d.getDate()}`;out.push(start===i-1?f(a):`${f(a)}–${f(b)}`);start=i}}return out.join(', ')}
function summaryText(){const c=calculations();const lines=[`On-Call | ${rangeLabel()}`];settings.names.forEach((name,t)=>{const inds=c.assigned.filter(x=>x.tech===t).map(x=>x.i);if(!inds.length)return;lines.push(`${name} — ${compactDates(inds)} — ${money(c.cents[t]/100)}`);const holidays=c.assigned.filter(x=>x.tech===t&&x.holiday);holidays.forEach(x=>lines.push(`${name} Holiday ${x.d.getMonth()+1}/${x.d.getDate()} — ${money(settings.rates.holiday)}`));if(holidays.length)lines.push(`${name} Total — ${money(c.totals[t])}`)});if(!c.assigned.length)lines.push('No days assigned');return lines.join('\n')}
function render(){renderWeek();renderTechs();renderDays();renderSummary();renderHistory()}
function renderWeek(){$('#weekRange').textContent=rangeLabel()}
function renderTechs(){const box=$('#techPicker');box.innerHTML='';settings.names.forEach((name,i)=>{const b=document.createElement('button');b.className='tech-btn';b.type='button';b.role='radio';b.ariaChecked=String(i===active);b.textContent=name;b.onclick=()=>{active=i;renderTechs();renderDays()};box.append(b)});$('#fullWeekTech').textContent=`to ${settings.names[active]}`;$('#fullWeekAmount').textContent=money(settings.rates.week)}
function renderDays(){const box=$('#daysGrid');box.innerHTML='';const c=calculations();c.days.forEach((d,i)=>{const rec=dayData(d),card=document.createElement('div');card.className=`day-card${rec.tech!==null?' assigned':''}${dateKey(d)===dateKey(new Date())?' today':''}`;card.tabIndex=0;card.role='button';card.setAttribute('aria-label',`${d.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}${rec.tech!==null?`, assigned to ${settings.names[rec.tech]}`:', unassigned'}`);const auto=holidayName(d);const base=i===0||i===6?settings.rates.weekend:settings.rates.weekday;card.innerHTML=`${rec.holiday?'<span class="holiday-dot">✦</span>':''}<div class="day-name">${d.toLocaleDateString('en-US',{weekday:'short'}).toUpperCase()}</div><div class="day-number">${d.getDate()}</div><div class="day-rate">${money(base)}</div><span class="day-tech">${rec.tech!==null?settings.names[rec.tech]:'Unassigned'}</span><button class="holiday-toggle ${rec.holiday?'active':''}" ${rec.tech===null?'disabled':''}>${rec.holiday?'✦ Holiday':'Holiday'}</button>`;const assign=()=>{setDayData(d,{tech:rec.tech===active?null:active,holiday:rec.tech===active?false:rec.holiday});render()};card.addEventListener('click',e=>{if(!e.target.closest('.holiday-toggle'))assign()});card.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('.holiday-toggle')){e.preventDefault();assign()}});card.querySelector('.holiday-toggle').onclick=e=>{e.stopPropagation();if(rec.tech===null)return;setDayData(d,{tech:rec.tech,holiday:!rec.holiday});render()};if(auto)card.title=`Company holiday: ${auto}`;box.append(card)});$('#coverageLabel').textContent=`${c.assigned.length} of 7 covered`}
function renderSummary(){const c=calculations(),box=$('#summaryRows');box.innerHTML='';settings.names.forEach((name,t)=>{const assigned=c.assigned.filter(x=>x.tech===t);if(!assigned.length)return;const row=document.createElement('div');row.className='summary-row';const h=assigned.filter(x=>x.holiday).length;row.innerHTML=`<span class="avatar">${name.charAt(0).toUpperCase()}</span><span><strong>${name}</strong><small>${compactDates(assigned.map(x=>x.i))}${h?` · ${h} holiday${h>1?'s':''}`:''}</small></span><b>${money(c.totals[t])}</b>`;box.append(row)});if(!c.assigned.length)box.innerHTML='<div class="empty">Choose a technician and assign their on-call days.</div>';$('#grandTotal').textContent=money(c.total);$('#summaryText').value=summaryText()}
function renderHistory(){$('#historyCount').textContent=histories.length;const box=$('#historyList');box.innerHTML=histories.length?'':'<div class="empty">No saved reports yet.</div>';histories.forEach((h,i)=>{const el=document.createElement('div');el.className='history-item';el.innerHTML=`<span><strong>${h.range}</strong><small>${h.saved}</small></span><span class="history-actions"><button class="mini-btn" data-copy>Copy</button><button class="mini-btn danger" data-delete>Delete</button></span>`;el.querySelector('[data-copy]').onclick=()=>copyText(h.text);el.querySelector('[data-delete]').onclick=()=>{histories.splice(i,1);save();renderHistory();toast('Report deleted')};box.append(el)})}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1900)}
async function copyText(text){try{await navigator.clipboard.writeText(text);toast('Summary copied')}catch{$('#summaryText').select();document.execCommand('copy');toast('Summary copied')}}
$('#prevWeek').onclick=()=>{weekStart=addDays(weekStart,-7);render()};$('#nextWeek').onclick=()=>{weekStart=addDays(weekStart,7);render()};
$('#weekPicker').onclick=()=>{const raw=prompt('Enter any date in the payroll week (YYYY-MM-DD):',dateKey(weekStart));if(raw&&/^\d{4}-\d{2}-\d{2}$/.test(raw)){weekStart=startOfWeek(parseKey(raw));render()}};
$('#clearWeek').onclick=()=>{if(confirm(`Clear all assignments for ${rangeLabel()}?`)){weekState().days={};save();render();toast('Week cleared')}};
$('#fullWeekBtn').onclick=()=>{Array.from({length:7},(_,i)=>addDays(weekStart,i)).forEach(d=>{const rec=dayData(d);setDayData(d,{tech:active,holiday:rec.holiday})});render();toast(`Full week assigned to ${settings.names[active]}`)};
$('#copyBtn').onclick=()=>copyText(summaryText());$('#shareBtn').onclick=async()=>{const text=summaryText();if(navigator.share)try{await navigator.share({title:'On-Call Payroll',text})}catch(e){if(e.name!=='AbortError')copyText(text)}else copyText(text)};
$('#saveReport').onclick=()=>{const c=calculations();if(!c.assigned.length)return toast('Assign at least one day first');histories.unshift({range:rangeLabel(),text:summaryText(),saved:new Date().toLocaleString()});histories=histories.slice(0,20);save();renderHistory();toast('Report saved')};
function openSettings(){const box=$('#nameInputs');box.innerHTML='';settings.names.forEach((n,i)=>{const l=document.createElement('label');l.textContent=`Technician ${i+1}`;l.innerHTML+=`<input data-name="${i}" value="${n.replaceAll('&','&amp;').replaceAll('"','&quot;')}">`;box.append(l)});$('#rateWeek').value=settings.rates.week;$('#rateWeekday').value=settings.rates.weekday;$('#rateWeekend').value=settings.rates.weekend;$('#rateHoliday').value=settings.rates.holiday;$('#settingsDialog').showModal()}
$('#settingsBtn').onclick=openSettings;$('#saveSettings').onclick=e=>{e.preventDefault();const names=[...document.querySelectorAll('[data-name]')].map(x=>x.value.trim()).filter(Boolean);if(names.length!==3)return toast('Enter all three technician names');settings={names,rates:{week:+$('#rateWeek').value,weekday:+$('#rateWeekday').value,weekend:+$('#rateWeekend').value,holiday:+$('#rateHoliday').value}};active=Math.min(active,2);save();$('#settingsDialog').close();render();toast('Settings saved')};
function registerWebTools(){const ctx=document.modelContext;if(!ctx?.registerTool)return;const register=tool=>{try{Promise.resolve(ctx.registerTool(tool)).catch(()=>{})}catch{}};register({name:'get_payroll_summary',title:'Get payroll summary',description:'Read the currently selected on-call week, assignments, and calculated payroll summary.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({week:rangeLabel(),summary:summaryText(),total:calculations().total})});register({name:'assign_on_call_days',title:'Assign on-call days',description:'Assign one or more dates in the visible payroll week to a technician and optionally mark them as holidays.',inputSchema:{type:'object',properties:{technician:{type:'string'},dates:{type:'array',items:{type:'string',pattern:'^\\d{4}-\\d{2}-\\d{2}$'},minItems:1},holidayDates:{type:'array',items:{type:'string',pattern:'^\\d{4}-\\d{2}-\\d{2}$'}}},required:['technician','dates'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{const tech=settings.names.findIndex(n=>n.toLowerCase()===String(input?.technician||'').toLowerCase());if(tech<0)throw new Error('Unknown technician');if(!Array.isArray(input.dates)||!input.dates.length)throw new Error('At least one date is required');const valid=new Set(Array.from({length:7},(_,i)=>dateKey(addDays(weekStart,i))));const holidays=new Set(input.holidayDates||[]);input.dates.forEach(k=>{if(!valid.has(k))throw new Error(`${k} is outside the visible payroll week`)});input.dates.forEach(k=>{const d=parseKey(k);setDayData(d,{tech,holiday:holidays.has(k)||Boolean(holidayName(d))})});render();return {week:rangeLabel(),technician:settings.names[tech],assignedDates:input.dates,summary:summaryText()}}})}
state=loadJson(STORE,{});render();registerWebTools();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
